version: '3'
services:
    database:
        image: 'mongo'
        container_name: 'MyMongoDB'
        environment: 
            - MONGO_INITDB_DATABASE=${MONGO_DB}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
        volumes: 
            - ./${MONGO_INIT_SCRIPT}:/docker-entrypoint-initdb.d/${MONGO_INIT_SCRIPT}:ro
            - ${MONGO_DATA_FOLDER}:/data/db
        ports:
            - '27017-27019:27017-27019'